// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRhi5nwAdtk4_BxhDMK4yqDxB55aMVQYM', // Using Android API key for web
    appId: '1:864463518345:web:...', // You'll need to add web app to get this
    messagingSenderId: '864463518345',
    projectId: 'lovebug-dating-app',
    authDomain: 'lovebug-dating-app.firebaseapp.com',
    storageBucket: 'lovebug-dating-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRhi5nwAdtk4_BxhDMK4yqDxB55aMVQYM',
    appId: '1:864463518345:android:e328d64a31088ed7e9a458',
    messagingSenderId: '864463518345',
    projectId: 'lovebug-dating-app',
    storageBucket: 'lovebug-dating-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeUes6CtrsIaKBhsKaXApU1QY5Tbr7sJ4',
    appId: '1:864463518345:ios:df887012fd93469de9a458',
    messagingSenderId: '864463518345',
    projectId: 'lovebug-dating-app',
    storageBucket: 'lovebug-dating-app.appspot.com',
    iosBundleId: 'com.lovebug.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeUes6CtrsIaKBhsKaXApU1QY5Tbr7sJ4',
    appId: '1:864463518345:ios:df887012fd93469de9a458',
    messagingSenderId: '864463518345',
    projectId: 'lovebug-dating-app',
    storageBucket: 'lovebug-dating-app.appspot.com',
    iosBundleId: 'com.lovebug.app',
  );
}
